spring:
  profiles:
    active:
    - dev
  
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/chat
#    username: postgres
#    password: voo12voo
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
#      hibernate.format_sql: true